version: '2'

services:

  solr:
    image: solr:5.4.1
    restart: always
    volumes:
      - ./solr:/opt/solr/server/solr
    ports:
      - 8984:8983

  compile:
    build:
      context: .
      dockerfile: Dockerfile-compile
    volumes:
      - .:/project

  gitclone:
    build: gitclone
    volumes:
      - ./gitclone/git:/git
    env_file:
      - docker.env

  importer:
    build:
      context: .
      dockerfile: Dockerfile-importer
    restart: always
    ports:
      - 9090:8080
    volumes:
      - ./gitclone/git:/git
      - ./import-files:/import-files
    environment:
      - GIT_INPUT_DIR=/git/adwquellen-daten
      - OUTPUT_DIR=/import-files
      - SOLR_IMPORT_CORE=adwquellen
      - SOLR_ONLINE_CORE=
    env_file:
      - docker.env
    